title: Youran Zhao's Personal Website
page-top-title: Get to Know Youran Zhao
top-section-bg-text: Cornell University - Operation Research and Information Engineering
home-subtitle: Youran ZHAO&ensp;|&ensp;Email:yz3385@cornell.edu
